export { default as RecommendedPagesWidget } from "./RecommendedPagesWidget";
export { default as SuggestedFriendsWidget } from "./SuggestedFriendsWidget";
export { default as HeaderWidget } from "./HeaderWidget";
export { default as PhotosWidget } from "./PhotosWidget";
export { default as VideosWidget } from "./VideosWidget";
export { default as BasicInfoWidget } from "./BasicInfoWidget";
export { default as StarFriendsWidget } from "./StarFriendsWidget";
export { default as FriendsFilterWidget } from "./FriendsFilterWidget";
export { default as PhotosFilterWidget } from "./PhotosFilterWidget";
